name: CI/CD Deploy to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main
    # Only run when PR is merged
    if: github.event.pull_request.merged == true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend:latest